apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: slack-notifier-role
  namespace: bookinfo
rules:
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["get", "list"]
