apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: slack-notifier-role-binding
  namespace: bookinfo
subjects:
- kind: ServiceAccount
  name: slack-notifier-sa
  namespace: bookinfo 
roleRef:
  kind: ClusterRole
  name: slack-notifier-role
  namespace: bookinfo
  apiGroup: rbac.authorization.k8s.io
