apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: pod-deletion-cronjob
  namespace: bookinfo
spec:
  schedule: "*/5 * * * *"  # Run every 5 minutes
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: kubectl
            image: kubectl:latest
            command:
            - /bin/sh
            - -c
            - kubectl delete pod productpage-v1-787cc89798-fqcq2 -n bookinfo
          restartPolicy: OnFailure
      backoffLimit: 4  # Adjust as needed
  successfulJobsHistoryLimit: 1
  failedJobsHistoryLimit: 3
  afterJobs:
  - jobTemplate:
      spec:
        serviceAccountName: slack-notifier-sa
        restartPolicy: OnFailure
        containers:
        - name: slack-notifier
          image: technosophos/slack-notify



 # Replace with the image that sends Slack notifications