apiVersion: v1
kind: Pod
metadata:
  name: slack-notifier-pod
  namespace: bookinfo
spec:
  serviceAccountName: slack-notifier-sa
  containers:
  - name: curl
    image: curlimages/curl:latest
    command:
    - /bin/sh
    - -c
    - 'curl -X POST -H "Content-type: application/json" \
       --data \'{"text":"Pod deletion job has completed in namespace your-namespace."}\' \
       https://hooks.slack.com/services/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'
  restartPolicy: OnFailure
